### ISSUE TITLE
hello,i just want to know if this work always detect out forgery area in both real and fake pic.

### ISSUE THREAD

**Issue by kkpssr** [HighwayWu/FOCAL#10]
thanks for the excellent work and idea, i notice there is kmeans algo with 2 cluster point in the code , So if the pic is absolutely a real pic the model also will give a fake area?

**Comment by akashlp27** [comment]
Hi, @kkpssr , I think the answer is yes, I have faced the same issue when testing on the some real images, I tried to increase the threshold , but the results were same.

**Comment by HighwayWu** [comment]
Sorry for the late reply. If the clustering method is kmeans with 2 clusters, then some areas of the real image will be inferred as false alarms. In this case, it will be more appropriate to use cluster adaptive algorithms, such as hdbscan clustering, which could better suppress false alarms.

**Comment by doteric** [comment]
Hey @HighwayWu 

> it will be more appropriate to use cluster adaptive algorithms, such as hdbscan clustering, which could better suppress false alarms.

Do you plan to support such in your tool as an option by any chance? Is there any way to decrease false alarms in your tool by any chance?

Big thank you 🙇

**Comment by HighwayWu** [comment]
Sorry for the late reply. False alarms may be further reduced by performing image-level detection. For example, setting a threshold to evaluate the normalized mutual information of extracted features.

**Comment by doteric** [comment]
@HighwayWu  
No problem at all, thanks for replying.  
Could you please further explain what exactly do you mean by `setting a threshold` and `normalized mutual information of extracted features`? I would appreciate it.
