### ISSUE TITLE
How to predict and evaluate real pictures by k-means?

### ISSUE THREAD

**Issue by yanzhelee** [HighwayWu/FOCAL#11]
The prediction results obtained by k-means clustering must be divided into two categories: fake and real, so how to use such results to evaluate the accuracy of the real dataset?

**Comment by Java001Cheng** [comment]
hi！How far have you gotten with this project?

**Comment by HighwayWu** [comment]
Thanks for your question. Using 2-cluster kmeans will inevitably produce certain false detections on real images. Additional filtering mechanisms are recommended, such as directly inferring that the current image is real when the average distance between real/fake categories is less than a fixed threshold.
