### ISSUE TITLE
Please provide the code for HDBSCAN clustering prediction

### ISSUE THREAD

**Issue by yanzhelee** [HighwayWu/FOCAL#12]
Hello author, I encountered a problem when trying to cluster using HDBSCAN, that is, the number of clusters often exceeds 2.
Could you please provide the HDBSCAN code mentioned in the paper?

**Comment by HighwayWu** [comment]
Thanks for your asking. More detailed code will be provided later. Furthermore, when HDBSCAN provides predictions for more than 2 categories, simply marking the category with the most elements as pristine (real) and the other categories as forged (fake).

**Comment by xmser** [comment]
Thank you for your masterpiece. Is there any follow-up for the HDBSCAN related code? Thank you very much~
