### ISSUE TITLE
Questions about the results in Tabel 1

### ISSUE THREAD

**Issue by yzhoulv** [HighwayWu/FOCAL#13]
I am extremely grateful for the authors' diligent efforts, yet I find myself perplexed regarding the results presented in Table 1. There seems to be a significant discrepancy between the outcomes of TruFor and Mvss-Net in comparison to the official paper. For instance, when considering TruFor with a fixed threshold of 0.5, the F1 score for CASIAv1 stands at 0.737, Coverage at 0.600, Columbia at 0.859, and Nist at 0.399. However, upon examination of FOCAL's Table 1, the results differ considerably, with CASIAv1 scoring 0.835, Coverage at 0.741, Columbia at 0.821, and Nist at 0.688. These differences far exceed the typical margin of error, leading to my confusion.

**Comment by HighwayWu** [comment]
Thanks for your question. This discrepancy is two-fold: 1) The test sets used are not exactly the same, e.g., TruFor added additional real data during the evaluation; 2) The metric (F1 score) used maybe different, e.g., the lower bound (random guess) of ''macro-f1'' we used is around 0.5. Therefore, it is recommended to first use TruFor/MVSS-Net to generate prediction results, and then use the SAME evaluation metric in [main.py](https://github.com/HighwayWu/FOCAL/blob/5c330e895490067c098076dbb859c532dfeb2ce1/main.py#L20) for a more unified evaluation.

**Comment by yzhoulv** [comment]
Thanks for your patience.
