### ISSUE TITLE
Train time

### ISSUE THREAD

**Issue by changchaoqun** [HighwayWu/FOCAL#16]
Hello, I used two A100 units for training during the training process, with 4000 data, 4 batchszie, and 1024 picture size. I found that it takes one hour to run one epoch. Is this time normal? In addition, may I ask the author how much pre-training data you trained this model at that time, how many epochs you ran in total, and how long you trained? Look forward to the author's reply, thank you very much.

**Comment by HighwayWu** [comment]
Thanks for your question. For ViT training, I used 4 A100s and set the batch size to 4. For an epoch of 4000 images, it took about 12 minutes (so taking one hour is not normal). It ran for a total of nearly 190 epochs and took 38 hours.

**Comment by changchaoqun** [comment]
Thank you! I wonder if the slow speed has something to do with the number of machines. Also, I find that the main.py code validates val after each batch instead of each epoch, is this the cause of the slowness? In addition, due to different tasks, I retrained the model on the document tampering dataset (the tampering area is small), and found that score of running 15 epochs is basically unchanged and very low. May I ask what parameters need to be adjusted or do you have any suggestions?
<img width="332" alt="微信图片_20240531113316" src="https://github.com/HighwayWu/FOCAL/assets/58622161/02f3743a-19bc-4b94-b89c-5dcc04dc10f3">

**Comment by changchaoqun** [comment]
I changed to FocalHRNet for training, but after a dozen epochs, the score is still very low and basically unchanged. Do I need to continue training? Also, document type tampering with pictures is different from natural scene tampering, I've been wondering whether to retrain model or fine-tune the model of your trained?

**Comment by HighwayWu** [comment]
1. Validation does not need to be performed on every batch. Please adjust it according to the amount of training data.
2. Sorry, we did not try to experiment on specific image types (such as document data). You may need to adjust certain parameters based on your experimental data, such as increasing the forged area by up-scaling to prevent it from disappearing during down-sampling operations adopted in HRNet or ViT.

**Comment by changchaoqun** [comment]
thanks,i will try it
