### ISSUE TITLE
About model

### ISSUE THREAD

**Issue by qiyuebobo** [HighwayWu/FOCAL#17]
dear author, I wanna know how to create fusion model including vit and Hrnet?

**Comment by qiyuebobo** [comment]
have you ever tried this method in document tamper detection ,such as DocTamper?

**Comment by HighwayWu** [comment]
Sorry for the late reply. In main.py, fused hrnet and vit are used for inference by default, refer to [L430](https://github.com/HighwayWu/FOCAL/blob/5c330e895490067c098076dbb859c532dfeb2ce1/main.py#L430).
In addition, we did not conduct experiments on specific types of document datasets such as DocTamper. You may need to adjust some parameters according to that dataset.

**Comment by qiyuebobo** [comment]
Thank you for your reply!
I had already trained your project several days ago using Doctamper on 5 4090 GPUs with a batch size of 5. However, the performance has been unsatisfactory:
- Epoch 8 PF1: 0.5742, PIOU: 0.0991 (training is still ongoing, with the FIoU improving by 1 percent every epoch).

**Comment by qiyuebobo** [comment]
Could you please provide information on the number of epochs you trained? I was unable to locate this detail in your paper.

**Comment by HighwayWu** [comment]
1. Please refer to this [issue](https://github.com/HighwayWu/FOCAL/issues/16) for details on the training epochs.
2. Our experimental parameters are set based on natural images, which may not be applicable to document images. In addition, the model's skeleton network (HRNet or ViT) may not be suitable for detecting document images. Generally speaking, the basic performance should not be so unsatisfactory. It is recommended to replace it with the [DTD network](https://github.com/qcf-568/DocTamper/blob/main/models/dtd.py) proposed by the author of DocTamper for training.

**Comment by qiyuebobo** [comment]
THANK YOU!
