### ISSUE TITLE
推理耗时

### ISSUE THREAD

**Issue by boreas-l** [HighwayWu/FOCAL#18]
直接clone工程到google colab上简单跑了一下demo，感觉耗时有点大吖，循环6次，平均3s多...大佬你那边测试耗时如何？我在论文上好像没看到。谢谢

**Comment by HighwayWu** [comment]
Thanks for your asking. The inference time (network inference + K-Means clustering) for HRNet is ~0.085 seconds / image, while for ViT is ~0.104 seconds / image.
