### ISSUE TITLE
migrate to the custom dataset

### ISSUE THREAD

**Issue by zzzjoey** [HighwayWu/FOCAL#19]
Thank you for sharing your excellent work.
Can this method be migrated to a custom dataset? At present, there are only box level annotations in the dataset, without pixel level annotations.

**Comment by HighwayWu** [comment]
Thank you for your attention. However, I'm not familiar with box prediction tasks like object detection, and it is difficult for me to provide migration assistance.

**Comment by zzzjoey** [comment]
Thanks for your answer. It seems to me that Image Forgery Detection is a task similar to segmentation rather than object detection, right?

**Comment by HighwayWu** [comment]
Yes, "image forgery localization" may be a more accurate description than "image forgery detection".
