### ISSUE TITLE
训练报错 training error RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by CongYep** [HighwayWu/FOCAL#4]
我发现当我使用('tampCOCO_sp_199999.npy', 1),   ('tampCOCO_cm_199429.npy', 1),   ('tampCOCO_bcm_199443.npy', 1)，这些数据集来训练时，会有以下提示错误：
File "main.py", line 428, in <module>
    model.train()
  File "main.py", line 296, in train
    batch_loss = self.focal.process(Ii, Mg, isTrain=True)
  File "main.py", line 195, in process
    batch_loss = torch.mean(torch.stack(info_nce_loss).squeeze())
RuntimeError: stack expects a non-empty TensorList
而使用('train_casia2_5123.npy', 40),   ('train_imd2020_2010.npy', 20) 来训练就不会报错。
我猜想是不是由于tampCOCO_sp、tampCOCO_cm、tampCOCO_bcm中存在大量的有image但没相应的mask的情况导致的。

-----------------------------------------------------------------------------------------------------------------------------------------------
English

I found that when I use datasets such as ('tampCOCO_sp199999. npy ', 1), ('tampCOCO_cm199429. npy', 1), and ('tampCOCO_bcm199443. npy ', 1) for training, the following error prompts appear:
File "main. py", line 428, in<module>
Model. train()
File "main. py", line 296, in train
Batch_ Loss=self. focal. process (Ii, Mg, isTrain=True)
File "main. py", line 195, in process
Batch_ Loss=torch. mean (torch. stack (info'nce_loss). squeeze())
RuntimeError: stack expectations a non empty TensorList
And using ('train_casia2-5123. npy ', 40), ('train_imd2020_2010. npy', 20) for training will not result in an error.
I guess it's because of tampCOCO_ Sp, tampCOCO_ Cm, tampCOCO_ There are a large number of cases in BCM where there are images but no corresponding masks.

**Comment by CongYep** [comment]
发现是我加载tampCOCO_sp、tampCOCO_cm、tampCOCO_bcm数据集的mask的时候没有正确找到路径的问题。图片和mask应该是一一对应的。
I found that the problem was that I did not find the correct path when loading the mask of the tampCOCO dataset.

**Comment by Cococc2** [comment]
请问   
![image](https://github.com/HighwayWu/FOCAL/assets/119996653/580e9a80-05fc-437c-93ed-a418e36b8064)
这些   .npy文件怎么获取

**Comment by CongYep** [comment]
看readme第三条命令
