### ISSUE TITLE
训练HRNet的时候报错 An error occurred while training HRNet， IndexError: The shape of the mask [64, 64] at index 0 does not match the shape of the indexed tensor [256, 256, 32] at index 0

### ISSUE THREAD

**Issue by CongYep** [HighwayWu/FOCAL#6]
An error occurred while training HRNet， IndexError: The shape of the mask [64, 64] at index 0 does not match the shape of the indexed tensor [256, 256, 32] at index 0

我的修改如下：
class FOCAL(nn.Module):
    def __init__(self, net_list=[('HRNet', '')]):

class ForgeryForensics():
    self.focal = FOCAL([  ('HRNet', ''),  ]).cuda()

报错 Error
Traceback (most recent call last):
  File "main.py", line 449, in <module>
    model.train()
  File "main.py", line 301, in train
    batch_loss = self.focal.process(Ii, Mg, isTrain=True)
  File "main.py", line 190, in process
    query = Fo_idx[Mg_idx == 0]
IndexError: The shape of the mask [64, 64] at index 0 does not match the shape of the indexed tensor [256, 256, 32] at index 0

**Comment by HighwayWu** [comment]
The augment "gt_ratio" should be 4 for HRNet, as HRNet outputs 1/4 resolution.

**Comment by CongYep** [comment]
OK，thank you
