### ISSUE TITLE
Faceforensics++数据集

### ISSUE THREAD

**Issue by xupinggl** [HighwayWu/FOCAL#8]
Hello, I would like to ask you about the Faceforensics++ dataset, I followed the instructions from https://github.com/ondyari/FaceForensics (as shown in Figure 1 below) and downloaded 1000 images, but there is no mask. can you please tell me, (1) Are these 1000 images used in your paper? (2) If yes, can you provide me the mask? If not, can you share with me the dataset you used? Thank you very much.

**Comment by xupinggl** [comment]
![image](https://github.com/HighwayWu/FOCAL/assets/102807353/0146cc8b-d854-402b-9c3e-e06718f8ec92)

**Comment by HighwayWu** [comment]
Thanks for your question. The FF++ data used in the FOCAL experiments can be downloaded from [here](https://drive.google.com/file/d/13FTwLZjO9QUiwpH7-iRFKAlkKQGRjWYy/view?usp=sharing).

**Comment by xupinggl** [comment]
Thank you so much for sharing!
